# Generated by Django 6.0.5 on 2026-08-22 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_en_papelera_ticket_fecha_eliminacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAdjunto',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='ticket_adjuntos/')),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_adjunto',
            },
        ),
    ]
