# Generated by Django 6.0.5 on 2026-08-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_usuario_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='grupo',
            field=models.CharField(choices=[('tecnologia', 'Tecnología'), ('sistema', 'Sistema'), ('davan_eleconstruc', 'Davan y Eleconstruc'), ('somos_deporte', 'Somos Deporte'), ('lompanes_alombarda', 'Lompanes y Alombarda'), ('gestion_humana', 'Gestión Humana'), ('proconsul_ipconstruc', 'Proconsul y Ipconstruc'), ('grupo_loscar', 'Grupo LosCar'), ('sata', 'SATA'), ('legal', 'Legal'), ('contabilidad', 'Contabilidad'), ('salud_movil', 'Salud Móvil'), ('nuevo_horizonte', 'Nuevo Horizonte')], default='tecnologia', max_length=30),
        ),
    ]
